<?php

/**
 * Created by PhpStorm.
 * User: a.ziethen
 * Date: 12.01.17
 * Time: 10:43
 */
class AzLizardsImport extends oxUBase
{
    protected $defaultVAT = 19;

    public function render()
    {
        $this->_generateLizardsXML();

        return parent::render(); // TODO: Change the autogenerated stub
    }

    protected function _generateLizardsXML()
    {
        echo "test";
    }
}