<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'export' => '/LizardsAndPumpkins/src/Export.php',
                'lizardsandpumpkins\\magentoconnector\\api\\api' => '/LizardsAndPumpkins/src/Api/Api.php',
                'lizardsandpumpkins\\magentoconnector\\api\\invalidhostexception' => '/LizardsAndPumpkins/src/Api/InvalidHostException.php',
                'lizardsandpumpkins\\magentoconnector\\api\\invalidurlexception' => '/LizardsAndPumpkins/src/Api/InvalidUrlException.php',
                'lizardsandpumpkins\\magentoconnector\\api\\requestfailedexception' => '/LizardsAndPumpkins/src/Api/RequestFailedException.php',
                'lizardsandpumpkins\\magentoconnector\\images\\imageexporter' => '/LizardsAndPumpkins/src/Images/ImageExporter.php',
                'lizardsandpumpkins\\magentoconnector\\images\\imagelinker' => '/LizardsAndPumpkins/src/Images/ImageLinker.php',
                'lizardsandpumpkins\\magentoconnector\\images\\imagescollector' => '/LizardsAndPumpkins/src/Images/ImagesCollector.php',
                'lizardsandpumpkins\\magentoconnector\\images\\nullimageexporter' => '/LizardsAndPumpkins/src/Images/NullImageExporter.php',
                'lizardsandpumpkins\\magentoconnector\\uploader' => '/LizardsAndPumpkins/src/Uploader.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\catalogmerge' => '/LizardsAndPumpkins/src/XmlBuilder/CatalogMerge.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\exception\\storenotsetoncategoryexception' => '/LizardsAndPumpkins/src/XmlBuilder/Exception/StoreNotSetOnCategoryException.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\invalidimagedefinitionexception' => '/LizardsAndPumpkins/src/XmlBuilder/InvalidImageDefinitionException.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\listingxml' => '/LizardsAndPumpkins/src/XmlBuilder/ListingXml.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\productbuilder' => '/LizardsAndPumpkins/src/XmlBuilder/ProductBuilder.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\stockbuilder' => '/LizardsAndPumpkins/src/XmlBuilder/StockBuilder.php',
                'lizardsandpumpkins\\magentoconnector\\xmlbuilder\\xmlstring' => '/LizardsAndPumpkins/src/XmlBuilder/XmlString.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd


